config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  devise_for :users
  root to: 'homes#top'
  root 'post_youtubers#index'

  resources :post_youtubers, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post_youtuber

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post_youtuber

end

app/models/post_youtuber.rb
class PostYoutuber < ApplicationRecord

  belongs_to :user
  attachment :image # ここを追加（_idは含めません）
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :ch_name, presence: true
  validates :image, presence: true
  validates :member, presence: true
  validates :url, presence: true


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_youtubers, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

end

app/controllers/api/v1/searches_controller.rb
class Api::V1::SearchesController < ApplicationController
  def index
    @items = Youtube::SearchService.new(params[:keyword], params[:order]).run
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_youtubers_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    post_youtuber = PostYoutuber.find(params[:post_youtuber_id])
    favorite = current_user.favorites.new(post_youtuber_id: post_youtuber.id)
    favorite.save
    redirect_to post_youtuber_path(post_youtuber)
  end

  def destroy
    post_youtuber = PostYoutuber.find(params[:post_youtuber_id])
    favorite = current_user.favorites.find_by(post_youtuber_id: post_youtuber.id)
    favorite.destroy
    redirect_to post_youtuber_path(post_youtuber)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    post_youtuber = PostYoutuber.find(params[:post_youtuber_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_youtuber_id = post_youtuber.id
    comment.save
    redirect_to post_youtuber_path(post_youtuber)
  end

  def destroy
    PostComment.find_by(id: params[:id], post_youtuber_id: params[:post_youtuber_id]).destroy
    redirect_to post_youtuber_path(params[:post_youtuber_id])
  end


 private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/post_youtubers_controller.rb
class PostYoutubersController < ApplicationController

  def new
      @post_youtuber = PostYoutuber.new
  end

  def create
    @post_youtuber = PostYoutuber.new(post_youtuber_params)
    @post_youtuber.user_id = current_user.id
    if @post_youtuber.save
      redirect_to post_youtubers_path
    else
      render :new
    end
  end

  def index
    @post_youtubers = PostYoutuber.page(params[:page]).reverse_order
  end

  def show
      @post_youtuber = PostYoutuber.find(params[:id])
      @post_comment = PostComment.new
  end

  def destroy
    @post_youtuber = PostYoutuber.find(params[:id])
    @post_youtuber.destroy
    redirect_to post_youtubers_path
  end



 private

  def post_youtuber_params
    params.require(:post_youtuber).permit(:ch_name, :image, :caption, :member, :url)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @post_youtubers = @user.post_youtubers.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_youtubers_helper.rb
module PostYoutubersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= javascript_pack_tag 'hello_vue' %>
<%= stylesheet_pack_tag 'hello_vue' %>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href=https://stitches.hyperyolo.com/output.css rel="stylesheet">
    <link rel="stylesheet" href=https://use.fontawesome.com/releases/v5.6.3/css/all.css integrity=sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/ crossorigin="anonymous">
    <title>Stitches</title>
  </head>
  <body><section class="font-sans h-screen w-full bg-cover text-center flex flex-col items-center justify-center"
  style="background:url(https://source.unsplash.com/random/1920x1080) no-repeat center;">
  <div class="bg-white text-black rounded-full h-16 w-16 flex items-center justify-center mb-8"><i
      class="fas fa-play ml-1"></i></div>
  <label for="" class="uppercase tracking-extrawide text-white text-xs font-hairline mt-8">Watch Video</label>
  <h3 class="text-white mx-auto max-w-sm mt-4 font-normal text-2xl leading-normal">Differentiate Yourself And Attract
    More Attention Sales And Profits</h3>
</section></body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Youtube</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-2" href="/"><%= image_tag('yt_logo_rgb_light.png',size: '10%') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_post_youtuber_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-4 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>新人YOUTUBERを応援するSNS</p>
            <%= image_tag('yt_logo_mono_dark.png') %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/post_youtubers/index.html.erb
<% @post_youtubers.each do |post_youtuber| %>
<div>

  <%= link_to post_youtuber_path(post_youtuber.id) do %>

  <%= attachment_image_tag post_youtuber, :image, :fill, 200, 200, fallback: "no_image.jpg"  %>

  <% end %>

  <p>チャンネル名：<%= post_youtuber.ch_name %></p>
  <p>チャンネル説明：<%= post_youtuber.caption %></p>
  <p>投稿者：<%= post_youtuber.user.name %></p>
  <p>チャンネルURL：<%= post_youtuber.url %></p>
  <p>登録者数：<%= post_youtuber.member %></p>
  <p><%= link_to "#{post_youtuber.post_comments.count} コメント", post_youtuber_path(post_youtuber.id) %></p>


</div>
<% end %>

<%= paginate @post_youtubers %>

app/views/post_youtubers/new.html.erb
<h1>投稿フォーム</h1>
<% if @post_youtuber.errors.any? %>
  <%= @post_youtuber.errors.count %>件のエラーが発生しました
  <% @post_youtuber.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model: @post_youtuber, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <h4>チャンネル名</h4>
  <%= f.text_field :ch_name %>
  <h4>チャンネル説明</h4>
  <%= f.text_area :caption %>
  <h4>登録者数</h4>
  <%= f.text_area :member %>
  <h4>チャンネルURL</h4>
  <%= f.text_area :url %>

  <%= f.submit '投稿' %>
<% end %>

app/views/post_youtubers/show.html.erb
<div class="post-body">

  <%= attachment_image_tag @post_youtuber, :image %>

  <p>チャンネル名：<%= @post_youtuber.ch_name %></p>
  <p>チャンネル説明：<%= @post_youtuber.caption %></p>
  <p>チャンネルURL：<%= @post_youtuber.url %></p>
  <p>登録者数：<%= @post_youtuber.member %></p>
  <p>ユーザーネーム：<%= @post_youtuber.user.name %></p>
  <p>投稿日時：<%= @post_youtuber.created_at.strftime('%Y/%m/%d') %></p>

  <% if @post_youtuber.user == current_user %>
    <%= link_to "削除", post_youtuber_path(@post_youtuber), method: :delete %>
  <% end %>

    <% if @post_youtuber.favorited_by?(current_user) %>
    <p>
      <%= link_to post_youtuber_favorites_path(@post_youtuber), method: :delete do %>
        ♥<%= @post_youtuber.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_youtuber_favorites_path(@post_youtuber), method: :post do %>
        ♡<%= @post_youtuber.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

</div>

<div class="comments">
  <p>コメント件数：<%= @post_youtuber.post_comments.count %></p>
  <% @post_youtuber.post_comments.each do |post_comment| %>
  <p><%= image_tag('sample-author1.jpg') %></p>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>

   <% if post_comment.user == current_user %>
  <div class="comment-delete">
  <%= link_to "削除", post_youtuber_post_comment_path(post_comment.post_youtuber, post_comment), method: :delete %>
  </div>
  <% end %>


 <% end %>
  </div>

<div class="new-comment">
  <%= form_with(model:[@post_youtuber, @post_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>



</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  <%= f.submit "変更を保存" %>

<% end %>

app/views/users/show.html.erb
<div class="profile-container">
  <h3 class="profile-name"><%= @user.name %></h3>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <% if @user.id == current_user.id %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>

</div>


<% @post_youtubers.each do |post_youtuber| %>
<div>
  <%= link_to post_youtuber_path(post_youtuber.id) do %>
    <%= attachment_image_tag post_youtuber, :image %>
  <% end %>
  <p>チャンネル名：<%= post_youtuber.ch_name %></p>
  <p>チャンネル説明：<%= post_youtuber.caption %></p>
  <p>登録者数：<%= post_youtuber.member %></p>
  <p>チャンネルURL：<%= post_youtuber.url %></p>
  <p>ユーザーネーム：<%= post_youtuber.user.name %></p>
</div>
<% end %>
<%= paginate @post_youtubers %>